version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-image
    container_name: frontend-container
    ports:
      -  "5173:5173"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-image
    container_name: backend-container
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env

volumes:
  frontend_node_modules: